const { contextBridge, ipcRenderer } = require('electron')

function on(channel, callback) {
  const handler = (_event, data) => callback(data)
  ipcRenderer.on(channel, handler)
  return () => ipcRenderer.removeListener(channel, handler)
}

contextBridge.exposeInMainWorld('electronAPI', {
  scanDirectory: (dirPath, force) => ipcRenderer.invoke('scan-directory', dirPath, force),
  generateThumbnail: (videoPath) => ipcRenderer.invoke('generate-thumbnail', videoPath),
  generateThumbnails: (videoPaths) => ipcRenderer.invoke('generate-thumbnails', videoPaths),
  getThumbnailUrl: (thumbnailPath) => ipcRenderer.invoke('get-thumbnail-url', thumbnailPath),
  generatePreviewFrame: (videoPath, seconds) => ipcRenderer.invoke('generate-preview-frame', videoPath, seconds),
  getVideoMetadata: (videoPath, options) => ipcRenderer.invoke('get-video-metadata', videoPath, options),
  onThumbnailProgress: (callback) => on('thumbnail-progress', callback),

  getSettings: () => ipcRenderer.invoke('get-settings'),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  listPlugins: () => ipcRenderer.invoke('plugins-list'),
  setPluginEnabled: (pluginId, enabled) => ipcRenderer.invoke('plugins-set-enabled', pluginId, enabled),
  installPlugin: () => ipcRenderer.invoke('plugins-install'),
  uninstallPlugin: (pluginId) => ipcRenderer.invoke('plugins-uninstall', pluginId),
  openPluginsDirectory: () => ipcRenderer.invoke('plugins-open-directory'),
  savePluginConfig: (pluginId, config) => ipcRenderer.invoke('plugins-save-config', pluginId, config),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  onSettingsChanged: (callback) => on('settings-changed', callback),
  setPrivacyPassword: (password) => ipcRenderer.invoke('privacy-set-password', password),
  unlockPrivacy: (password) => ipcRenderer.invoke('privacy-unlock', password),

  remoteGetState: () => ipcRenderer.invoke('remote-get-state'),
  remoteSaveSettings: (settings) => ipcRenderer.invoke('remote-save-settings', settings),
  remoteCopyEndpoint: () => ipcRenderer.invoke('remote-copy-endpoint'),
  remoteCopyToken: () => ipcRenderer.invoke('remote-copy-token'),
  remoteRotateToken: () => ipcRenderer.invoke('remote-rotate-token'),
  remoteCreatePairingCode: () => ipcRenderer.invoke('remote-create-pairing-code'),
  remoteCopyPairingCode: (pairingCode) => ipcRenderer.invoke('remote-copy-pairing-code', pairingCode),
  remoteRemovePairedDevice: (deviceId) => ipcRenderer.invoke('remote-remove-paired-device', deviceId),
  remoteApprovePairingRequest: (requestId) => ipcRenderer.invoke('remote-approve-pairing-request', requestId),
  remoteRejectPairingRequest: (requestId) => ipcRenderer.invoke('remote-reject-pairing-request', requestId),
  onRemoteAccessState: (callback) => on('remote-access-state', callback),
  onRemotePlayOnDesktop: (callback) => on('remote-play-on-desktop', callback),

  selectDirectory: () => ipcRenderer.invoke('select-directory'),
  selectVideoDirectory: () => ipcRenderer.invoke('select-video-directory'),
  openVideoFile: () => ipcRenderer.invoke('open-video-file'),
  allowVideoFile: (filePath) => ipcRenderer.invoke('allow-video-file', filePath),

  showInFolder: (filePath) => ipcRenderer.invoke('show-in-folder', filePath),
  getFileUrl: (filePath) => ipcRenderer.invoke('get-file-url', filePath),
  getPlaybackState: (filePath) => ipcRenderer.invoke('get-playback-state', filePath),
  savePlaybackState: (filePath, statePatch) => ipcRenderer.invoke('save-playback-state', filePath, statePatch),
  getVideoAnalysis: (filePath) => ipcRenderer.invoke('video-analysis-get', filePath),
  listSavedVideoAnalysis: (videos) => ipcRenderer.invoke('video-analysis-list-saved', videos),
  deleteSavedVideoAnalysis: (resultPath) => ipcRenderer.invoke('video-analysis-delete-saved', resultPath),
  startVideoAnalysis: (filePath) => ipcRenderer.invoke('video-analysis-start', filePath),
  cancelVideoAnalysis: (jobId) => ipcRenderer.invoke('video-analysis-cancel', jobId),
  getVideoAnalysisJob: () => ipcRenderer.invoke('video-analysis-job'),
  getVideoAnalysisOutputDir: () => ipcRenderer.invoke('video-analysis-get-output-dir'),
  selectVideoAnalysisOutputDir: () => ipcRenderer.invoke('video-analysis-select-output-dir'),
  openVideoAnalysisOutputDir: () => ipcRenderer.invoke('video-analysis-open-output-dir'),
  getVideoAnalysisModelDir: () => ipcRenderer.invoke('video-analysis-get-model-dir'),
  getDefaultVideoAnalysisModelDir: () => ipcRenderer.invoke('video-analysis-get-default-model-dir'),
  selectVideoAnalysisModelDir: () => ipcRenderer.invoke('video-analysis-select-model-dir'),
  openVideoAnalysisModelDir: () => ipcRenderer.invoke('video-analysis-open-model-dir'),
  getVideoAnalysisRuntimeConfig: () => ipcRenderer.invoke('video-analysis-get-runtime-config'),
  saveVideoAnalysisRuntimeConfig: (config) => ipcRenderer.invoke('video-analysis-save-runtime-config', config),
  resetVideoAnalysisRuntimeConfig: () => ipcRenderer.invoke('video-analysis-reset-runtime-config'),
  getVideoAnalysisVlmState: () => ipcRenderer.invoke('video-analysis-vlm-state'),
  getVideoAnalysisVlmModelOptions: () => ipcRenderer.invoke('video-analysis-vlm-model-options'),
  saveVideoAnalysisVlmConfig: (patch) => ipcRenderer.invoke('video-analysis-vlm-save-config', patch),
  selectVideoAnalysisVlmModelFile: () => ipcRenderer.invoke('video-analysis-vlm-select-model-file'),
  selectVideoAnalysisVlmServerExecutable: () => ipcRenderer.invoke('video-analysis-vlm-select-server-executable'),
  listVideoAnalysisVlmHfFiles: (patch) => ipcRenderer.invoke('video-analysis-vlm-hf-list-files', patch),
  selectVideoAnalysisVlmHfFile: (file) => ipcRenderer.invoke('video-analysis-vlm-hf-select-file', file),
  listVideoAnalysisLocalVlmFiles: () => ipcRenderer.invoke('video-analysis-vlm-local-list-files'),
  selectVideoAnalysisLocalVlmFile: (filePath) => ipcRenderer.invoke('video-analysis-vlm-local-select-file', filePath),
  downloadVideoAnalysisVlmModel: (selection) => ipcRenderer.invoke('video-analysis-vlm-download', selection),
  startVideoAnalysisVlmService: () => ipcRenderer.invoke('video-analysis-vlm-start'),
  stopVideoAnalysisVlmService: () => ipcRenderer.invoke('video-analysis-vlm-stop'),
  onVideoAnalysisEvent: (callback) => on('video-analysis-event', callback),
  onVideoAnalysisVlmEvent: (callback) => on('video-analysis-vlm-event', callback),
  checkFfmpeg: () => ipcRenderer.invoke('check-ffmpeg'),

  updaterGetStatus: () => ipcRenderer.invoke('updater-get-status'),
  updaterCheck: () => ipcRenderer.invoke('updater-check'),
  updaterDownload: () => ipcRenderer.invoke('updater-download'),
  updaterInstall: () => ipcRenderer.invoke('updater-install'),
  onUpdaterStatus: (callback) => on('updater-status', callback),

  checkMpv: () => ipcRenderer.invoke('check-mpv'),
  downloadMpv: () => ipcRenderer.invoke('download-mpv'),
  mpvPlay: (filePath, options = {}) => ipcRenderer.invoke('mpv-play', filePath, options),
  setMediaPlaybackActive: (active) => ipcRenderer.invoke('set-media-playback-active', active),
  mpvSetHostBounds: (bounds) => ipcRenderer.invoke('mpv-set-host-bounds', bounds),
  mpvStop: () => ipcRenderer.invoke('mpv-stop'),
  mpvIsPlaying: () => ipcRenderer.invoke('mpv-is-playing'),
  mpvGetState: () => ipcRenderer.invoke('mpv-get-state'),
  mpvCommand: (method, ...args) => ipcRenderer.invoke('mpv-command', method, ...args),
  mpvSeekTo: (position) => ipcRenderer.invoke('mpv-command', 'seekTo', position),
  mpvSeekRelative: (delta) => ipcRenderer.invoke('mpv-command', 'seekRelative', delta),
  mpvCyclePause: () => ipcRenderer.invoke('mpv-command', 'cyclePause'),
  mpvSetPaused: (paused) => ipcRenderer.invoke('mpv-command', 'setPaused', paused),
  mpvSetVolume: (volume) => ipcRenderer.invoke('mpv-command', 'setVolume', volume),
  mpvSetMuted: (muted) => ipcRenderer.invoke('mpv-command', 'setMuted', muted),
  mpvToggleMute: () => ipcRenderer.invoke('mpv-command', 'toggleMute'),
  mpvSetSpeed: (speed) => ipcRenderer.invoke('mpv-command', 'setSpeed', speed),
  mpvCycleSpeed: () => ipcRenderer.invoke('mpv-command', 'cycleSpeed'),
  mpvSetAudioTrack: (trackId) => ipcRenderer.invoke('mpv-command', 'setAudioTrack', trackId),
  mpvCycleAudioTrack: () => ipcRenderer.invoke('mpv-command', 'cycleAudioTrack'),
  mpvSetSubtitleTrack: (trackId) => ipcRenderer.invoke('mpv-command', 'setSubtitleTrack', trackId),
  mpvCycleSubtitleTrack: () => ipcRenderer.invoke('mpv-command', 'cycleSubtitleTrack'),
  mpvSetSubtitleVisible: (visible) => ipcRenderer.invoke('mpv-command', 'setSubtitleVisible', visible),
  mpvToggleSubtitleVisible: () => ipcRenderer.invoke('mpv-command', 'toggleSubtitleVisible'),
  mpvSetSubtitleScale: (scale) => ipcRenderer.invoke('mpv-command', 'setSubtitleScale', scale),
  mpvSetLoopMode: (mode) => ipcRenderer.invoke('mpv-command', 'setLoopMode', mode),
  mpvSetABLoop: (a, b) => ipcRenderer.invoke('mpv-command', 'setABLoop', a, b),
  mpvClearABLoop: () => ipcRenderer.invoke('mpv-command', 'clearABLoop'),
  mpvScreenshot: () => ipcRenderer.invoke('mpv-command', 'screenshot'),
  selectMpvPath: () => ipcRenderer.invoke('select-mpv-path'),
  onMpvState: (callback) => on('mpv-state', callback),
  onMpvEnded: (callback) => on('mpv-ended', callback),
  onMpvEvent: (callback) => on('mpv-event', callback),
  onMpvError: (callback) => on('mpv-error', callback),
  onMpvDownloadProgress: (callback) => on('mpv-download-progress', callback),

  onPlayerShortcut: (callback) => on('player-shortcut', callback)
})
